// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-u-4yohnveRtzDepe2Eqzr7_evNe9Y-A',
    appId: '1:875391192398:web:009fc7d7ff30f9d223221f',
    messagingSenderId: '875391192398',
    projectId: 'uptodo-d4dde',
    authDomain: 'uptodo-d4dde.firebaseapp.com',
    storageBucket: 'uptodo-d4dde.appspot.com',
    measurementId: 'G-2VWTGSVY6Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-S6EvYU39mjIu9gO-z50xPhrhN0PVkd4',
    appId: '1:875391192398:android:b2f2f4956492ff5023221f',
    messagingSenderId: '875391192398',
    projectId: 'uptodo-d4dde',
    storageBucket: 'uptodo-d4dde.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRH1510_bkszzfiCISCO-m59RlGvX_b-c',
    appId: '1:875391192398:ios:7227e69e26f93a9a23221f',
    messagingSenderId: '875391192398',
    projectId: 'uptodo-d4dde',
    storageBucket: 'uptodo-d4dde.appspot.com',
    iosBundleId: 'com.example.upTodo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRH1510_bkszzfiCISCO-m59RlGvX_b-c',
    appId: '1:875391192398:ios:7227e69e26f93a9a23221f',
    messagingSenderId: '875391192398',
    projectId: 'uptodo-d4dde',
    storageBucket: 'uptodo-d4dde.appspot.com',
    iosBundleId: 'com.example.upTodo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-u-4yohnveRtzDepe2Eqzr7_evNe9Y-A',
    appId: '1:875391192398:web:e455d597aa57cfd323221f',
    messagingSenderId: '875391192398',
    projectId: 'uptodo-d4dde',
    authDomain: 'uptodo-d4dde.firebaseapp.com',
    storageBucket: 'uptodo-d4dde.appspot.com',
    measurementId: 'G-1XXHCH198J',
  );
}
